dist: xenial
language: csharp
mono: none
sudo: required
git:
  depth: 1
addons:
  snaps: 
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
  
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - cd src
  - dotnet restore
  - dotnet build
  - dotnet test
