name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.303
    - name: Install dependencies
      run: dotnet restore src/MusicLibrary.sln
    - name: Build
      run: dotnet build src/MusicLibrary.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/MusicLibrary.sln --no-restore --verbosity normal
